name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - master
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  linter:
    name: Linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: golangci-lint
        # NOTE: https://github.com/golangci/golangci-lint-action/releases/tag/v8.0.0
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601
        with:
          version: v2.5.0

  vet:
    name: Go Vet
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: go vet
        run: go vet ./...

  static-check:
    name: Static-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: static-check
        # NOTE: https://github.com/dominikh/staticcheck-action/releases/tag/v1.4.0
        uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2
        with:
          install-go: false

  tests:
    name: Tests
    permissions:
      contents: read
      pull-requests: write
    env:
      GO_ENV: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.24', '1.25' ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.version }}
      - name: Run tests
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        if: matrix.version == '1.25'
        # NOTE: https://github.com/codecov/codecov-action/releases/v5.5.0
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
